# Deploy to WP.org
name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running NPM Install & Build For Gutenberg
        run: |
          npm install --silent && npm run build
      - name: Running NPM Install & Build for Admin Panel
        run: |
          cd includes/Admin/Settings && npm install --silent && npm run prod && cd ../../..
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
