# Deploy to WP.org
name: Deploy to WordPress.org

on:
  push:
    branches:
      - latest
    tags:
    - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running NPM Install & Build
        run: |
          npm install && npm run build && cd includes/Admin/Settings && npm install && npm run build && cd ../../..